area/module:
  - changed-files:
    - any-glob-to-any-file: 'modules/**'

area/backend:
  - changed-files:
    - any-glob-to-any-file: 'backends/**'

area/plugin:
  - changed-files:
    - any-glob-to-any-file: 'plugins/**'

area/lib:
  - changed-files:
    - any-glob-to-any-file: 'lib/**'

area/theme:
  - changed-files:
    - any-glob-to-any-file: 'themes/**'

area/installer:
  - changed-files:
    - any-glob-to-any-file: 'installer/**'

area/cli:
  - changed-files:
    - any-glob-to-any-file: 'kall'

area/docs:
  - changed-files:
    - any-glob-to-any-file: 'website/**'

area/ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

area/schema:
  - changed-files:
    - any-glob-to-any-file: 'schemas/**'
